[package]
name = "ctf-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
object = "0.28"
arrayref = "0.3"
flate2 = "1.0"
num_enum = "0.5"
clap = { version = "3.1.8", features = ["derive"] }
quote = "1.0"
proc-macro2 = "1.0"
syn = "1.0"
prettyplease = "0.1"
