[package]
name = "ctf-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
arrayref = "0.3"
clap = { version = "3.1.8", features = ["derive"] }
flate2 = "1.0"
num_enum = "0.5"
object = "0.28"
prettyplease = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
